// Code generated by MockGen. DO NOT EDIT.
// Source: concepter/concepter.go

// Package concepter is a generated GoMock package.
package main

import (
	context "context"
	sentence "optimization/internal/pkg/sentence"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// GetByTemplate mocks base method.
func (m *MockRepository) GetByTemplate(ctx context.Context, j sentence.Sentence) ([]sentence.Sentence, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTemplate", ctx, j)
	ret0, _ := ret[0].([]sentence.Sentence)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTemplate indicates an expected call of GetByTemplate.
func (mr *MockRepositoryMockRecorder) GetByTemplate(ctx, j interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTemplate", reflect.TypeOf((*MockRepository)(nil).GetByTemplate), ctx, j)
}
